package src.mybatis.model;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.BOX_OFFICE
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    private Double boxOffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.SURNAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.ID
     *
     * @return the value of PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.ID
     *
     * @param id the value for PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.BOX_OFFICE
     *
     * @return the value of PUBLIC.DOCTOR.BOX_OFFICE
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public Double getBoxOffice() {
        return boxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.BOX_OFFICE
     *
     * @param boxOffice the value for PUBLIC.DOCTOR.BOX_OFFICE
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public void setBoxOffice(Double boxOffice) {
        this.boxOffice = boxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @return the value of PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @param name the value for PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.DEPARTMENT_ID
     *
     * @return the value of PUBLIC.DOCTOR.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.DEPARTMENT_ID
     *
     * @param departmentId the value for PUBLIC.DOCTOR.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.SURNAME
     *
     * @return the value of PUBLIC.DOCTOR.SURNAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.SURNAME
     *
     * @param surname the value for PUBLIC.DOCTOR.SURNAME
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}