package src.mybatis.dao;

import src.mybatis.model.Doctor;

import java.util.List;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    Doctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int updateByPrimaryKey(Doctor record);
}