package src.mybatis.dao;

import src.mybatis.model.Patient;

import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PATIENT
     *
     * @mbg.generated Tue Apr 18 20:09:24 EEST 2023
     */
    int updateByPrimaryKey(Patient record);
}